### PR TITLE
metadata: wikipedia.py: Now returns empty dict in case error occurs 

### PR DESCRIPTION
**Pull request by manu-chroma**
Update: Added .travis.yml file in the dev branch

### CODE REVIEW

**Comment by kylepjohnson** [comment]
@manu-chroma Sorry, this PR fell between the cracks.

I see that the build is failing for this. Do you still want me to accept this?

**Comment by manu-chroma** [comment]
@kylepjohnson this branch didn't have a `.travis.yaml` file initially. (Reason for initial build fail)

Now, the tests because of which the build is failing are for a different feature and not this one.

Here's a snippet from the build log.

```
Traceback (most recent call last):
  File "/home/travis/build/cltk/cltk_api/tests.py", line 102, in test_pos_latin_ngram123
    self.assertEqual(response.status, '200 OK')
AssertionError: '500 INTERNAL SERVER ERROR' != '200 OK'
- 500 INTERNAL SERVER ERROR
+ 200 OK
```

I think it's safe to merge this PR. :smile:

**Comment by kylepjohnson** [comment]
Ok, thanks for this. Please keep an eye on the build and make any necessary fixes should this not go right :)

**Comment by kylepjohnson** [comment]
https://travis-ci.org/cltk/cltk_api/builds/120478780

**Comment by manu-chroma** [comment]
@kylepjohnson https://github.com/cltk/cltk_api/blob/feature/expose_cltk_core/tests.py#L84
This test is failing. 

I'll try running tests locally and see if I can fix it.

**Pull request merged**
